# -*- coding: utf-8 -*-
from __future__ import annotations

COGNITIVE_PAGE_TYPES = {
    "cover",
    "source_map",
    "experts",
    "library_lens",
    "core_question",
    "baseline_delta",
    "concept_anchor",
    "definition",
    "rank_map",
    "round",
    "round_opening",
    "response_graph",
    "case_shock",
    "clash",
    "moderator_crack",
    "cognitive_upgrade",
    "qa",
    "insight",
    "open_questions",
    "tension_map",
    "future_bets",
    "ending",
}

PAGE_LAYOUTS = {
    "cover": "reading_brief_4zone",
    "source_map": "reading_brief_4zone",
    "experts": "reading_brief_4zone",
    "library_lens": "magazine_focus",
    "core_question": "magazine_focus",
    "baseline_delta": "evolution_ladder",
    "concept_anchor": "reading_brief_4zone",
    "definition": "reading_brief_4zone",
    "rank_map": "tension_bars",
    "round": "stance_spectrum",
    "round_opening": "magazine_focus",
    "response_graph": "stance_spectrum",
    "case_shock": "case_file",
    "clash": "clash_courtroom",
    "moderator_crack": "magazine_focus",
    "cognitive_upgrade": "evolution_ladder",
    "qa": "question_wall",
    "insight": "reading_brief_4zone",
    "open_questions": "question_wall",
    "tension_map": "tension_bars",
    "future_bets": "question_wall",
    "ending": "magazine_focus",
}
